create schema cars;
use cars;
-- READ DATA --
SELECT * FROM car_dekho;

-- TOTAL CARS: TO GET A COUNT OF TOTAL RECORDS ---
SELECT COUNT(*) FROM car_dekho;

-- THE MANAGER ASKED THE EMPLOYEE HOW MANY CARS WILL BE AVAILABLE IN 2023? --
SELECT COUNT(*) FROM car_dekho WHERE year = 2023; 

-- THE MANAGER ASKED THE EMPLOYEE HOW MANY CARS ARE AVAIABLE IN 2020,2021,2022 --
SELECT COUNT(*) FROM car_dekho WHERE year = 2020;  #74
SELECT COUNT(*) FROM car_dekho WHERE year = 2021;  #7
SELECT COUNT(*) FROM car_dekho WHERE year = 2022;  #7
-- BY USING GROUP BY
SELECT COUNT(*) FROM car_dekho WHERE YEAR IN (2020,2021,2022) GROUP BY YEAR;

-- CLIENT ASKED ME TO PRINT ONLY THE TOTAL OF ALL CARS BY YEAR. --
SELECT year, COUNT(year) FROM car_dekho GROUP BY year;

-- CLIENT ASKED TO CAR DEALER AGENT HOW MANY DIESEL CARS WILL THERE BE IN 2020? --
SELECT COUNT(*) FROM car_dekho WHERE year = 2020 AND fuel = "Diesel";

-- CLIENT REQUESTED A CAR DEALER AGENT HOW MANY PETROL CARS WILL THERE BE IN 2020? --
SELECT COUNT(*) FROM car_dekho WHERE year = 2020 AND fuel = "Petrol";

-- THE MANAGER TOLD THE EMPLOYEE TO GIVE A PRINT OF ALL THE FUEL CARS(PETROL, DIESEL,CNG) COME BY ALL YEAR? --
SELECT year, COUNT(*) FROM car_dekho WHERE fuel = "Petrol" GROUP BY year;
SELECT year, COUNT(*) FROM car_dekho WHERE fuel = "Diesel" GROUP BY year;
SELECT year, COUNT(*) FROM car_dekho WHERE fuel = "CNG" GROUP BY year;

-- MANAGER SAID IN WHICH YEAR MORE THAN 100 CARS ARE COME FOR SELLING, WHICH YEAR HAD MORE THAN 100 CARS? --
SELECT year, count(*) from car_dekho GROUP BY year HAVING COUNT(*) > 100;

-- THE MANAGER SAID TO THE EMPLOYEE, WE NEED A COMPLETE LIST OF ALL CARS COUNT DETAILS BETWEEN 2015 AND 2023; --
SELECT  COUNT(year) FROM car_dekho WHERE year BETWEEN 2015 AND 2023; 

-- THE MANAGER SAID TO THE EMPLOYEE ALL CARS DETAILS BETWEEN 2015 TO 2023 ;
SELECT * FROM car_dekho WHERE YEAR BETWEEN 2015 AND 2023;

-- END ---




















